---
# global_settings are handled by puppet


global_params:
  - name: 'enable-puppetlabs-repo'
    value: 'false'
  - name: 'enable-puppetlabs-pc1-repo'
    value: 'false'
  - name: 'enable-puppet5'
    value: 'true'
  - name: 'enable-epel'
    value: 'false'
  - name: 'enable-norcams-epel'
    value: 'true'
  - name: 'enable-norcams-repo'
    value: 'true'
  - name: 'puppet_systemd_firstboot'
    value: 'true'
  - name: 'run-puppet-in-installer'
    value: 'true'
  - name: 'time-zone'
    value: 'Europe/Oslo'
  - name: 'ntp-server'
    value: 'no.pool.ntp.org'


subnets:
  name: 'mgmt.iaas.vagrant.intern'
  network: '10.100.200.0'
  cidr: '24'
  domain_ids: ''
  tftp_id: ''

media:
  name: 'CentOS download.iaas.uio.no'
  os_family: 'Redhat'
  path: ''

operatingsystems:
  centos7:
    name: 'CentOS'
    family: 'Redhat'
    major: '7'
    minor: '9.2009'
    architectures:
      - 'x86_64'
    media:
      - 'CentOS download.iaas.uio.no'
    ptables:
      - 'norcams-Kickstart default'
      - 'norcams-Kickstart default uefi'
    provisioningtemplates:
      - 'norcams-Kickstart default'
      - 'norcams-Kickstart default PXEGrub2'
      - 'norcams-Kickstart default PXELinux'

hostgroups:
  base:
    name: 'base'
    architecture: 'x86_64'
    operatingsystem: 'CentOS 7.9.2009'
    environment: 'production'
    pxe_loader: 'PXELinux BIOS'
    media: 'CentOS download.iaas.uio.no'
    ptable: 'norcams-Kickstart default'
    subnet: 'mgmt'
    parameters:
        - { 'name': 'enable-puppetlabs-puppet5-repo', 'value': 'true', 'parameter_type': 'string' }
  storage:
    name: 'storage'
    parent: 'base'
  compute:
    name: 'compute'
    parent: 'base'
